// vue-jsx-ts/src/components/Private.tsx
import { Vue, Prop, Component } from "vue-property-decorator";
import { VNode } from "Vue";

@Component({})
export default class Private extends Vue {
  @Prop({ required: true, type: Object })
  public readonly auth!: any;

  private message: string = "";

  created(): void {
    fetch("/private", {
      headers: {
        Authorization: `Bearer ${this.auth.getAccessToken()}`,
      },
    }) // DEVNOTE: cc. proxy => vue.config.js
      .then((response) => {
        if (response.ok) return response.json();
        throw new Error("Network response was not ok.");
      })
      .then((response) => {
        return (this.message = response.message);
      })
      .catch((error) => {
        return (this.message = error.message);
      });
  }

  render(h: Function): VNode {
    return (
      <div>
        <h1>Private</h1>
        <p>{this.message}</p>
      </div>
    );
  }
}

// react/src/Private.js
import React, { Component } from 'react';

export default class Private extends Component {
    state = {
        message: "",
    };

    componentDidMount() {
        fetch("/private", {
            headers: {
                Authorization: `Bearer ${this.props.auth.getAccessToken()}`,
            },
        }) // DEVNOTE: relative path even though domain is http://localhost:3001 (which would trigger a CORS violation anyway); create-react-app has support for "proxy" property in package.json which will proxy any calls from "http://localhost:3000" over to "http://localhost:3001". This allows us to maintain short flat relative urls but also conveniently avoids the cross origin resource sharing issues sporned from self-contained development environments.
            .then((response) => {
                if(response.ok) return response.json();
                throw new Error("Network response was not ok.");
            })
            .then((response) => {
                return this.setState({
                    message: response.message,
                });
            })
            .catch((error) => {
                return this.setState({
                    message: error.message,
                });
            });
    }

    render() {
        return <p>{ this.state.message }</p>;
    }
}
