// react/src/Profile.js
import React, { Component } from 'react';

export default class Profile extends Component {
    //DEVNOTE: class field syntax as oppose to declaring/initialising within a constructor()
    state = {
        profile: null,
        error: "",
    }

    componentDidMount() {
        this.loadUserProfile();
    }

    loadUserProfile() {
        this.props.auth.getProfile((profile, error) => {
            this.setState({profile, error});
        });
    }

    render() {
        const { profile } = this.state;
        
        if(!profile) return null;

        return (
            <>
                <h1>Profile</h1>
                <p>{ profile.nickname }</p>
                <img src={ profile.pic } alt="User profile avatar" style={ {maxWidth: 50, maxHeight: 50} } />
                {/* DEVNOTE: different providers may have standards for the fields they collect and the property names data is assigned to */}
                <pre>{ JSON.stringify(profile, null, 4) }</pre>
            </>
        );
    }
}

// vue-jsx-ts/src/components/Profile.tsx
import { Vue, Prop, Component } from "vue-property-decorator";
import { VNode } from "Vue";
import { directive } from "vue/types/umd";

interface ProfileType {
  sub: string;
  nickname: string;
  name: string;
  email: string;
  email_verified: boolean;
  picture: string;
  updatedAt: string;
}

@Component
export default class Profile extends Vue {
  @Prop({ required: true, type: Object })
  public readonly auth!: any;

  private profile: any | null = null;
  private error: string = "";

  beforeMount() {
    this.loadUserProfile();
  }

  private loadUserProfile() {
    this.auth.getProfile((profile: ProfileType, error: any) => {
      this.profile = profile;
      this.error = error;
    });
  }

  render(h: Function): VNode {
    return (
      <div>
        <h1>Profile</h1>
        {this.profile && (
          <div>
            <p>{this.profile.nickname}</p>
            <img
              src={this.profile.pic}
              alt="User profile avatar"
              style={{ maxWidth: "50px", maxHeight: "50px" }}
            />
            <pre>{JSON.stringify(this.profile, null, 4)}</pre>
          </div>
        )}
      </div>
    );
  }
}
